openapi: "3.0.0"
info:
  version: 1.0.0
  title: User API
  description: An API for managing user data
servers:
- url: http://localhost:3000
  description: Dummy API
paths:
  /user:
    get:
      summary: Returns the user data
      responses:
        '200':
          description: A JSON object of user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      balance:
                        type: integer
                      transactionHistory:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            amount:
                              type: integer
                            type:
                              type: string
                            date:
                              type: string
                              format: date-time
                      friends:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
